// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncuidluikeknatuqiazj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jdWlkbHVpa2VrbmF0dXFpYXpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTUzMzAsImV4cCI6MjA2MTI3MTMzMH0.0rcidWCWWwN3oAioxwjXBUrUyt8_iaJsZuhjwHSsD9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);